name: CI

on:
  workflow_call:

jobs:

  check_ci:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: ./node_modules
        key: node_modules-${{ github.run_id }}
          
    - name: Check format
      run: npm run check-prettier

    - name: Run eslint
      run: npm run check-eslint

    - name: Run test
      run: npm test
