name: Build documentation

on:
  workflow_call:

jobs:
  build_doc:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./.venv_vizzu_story
          key: venv-vizzu-story-${{ github.run_id }}

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: nodemodules-vizzu-story-${{ github.run_id }}

      - name: Touch dev environment
        run: make touch-dev

      - name: Touch dev-js environment
        run: make touch-dev-js

      - name: Build documentation
        run: make doc
