name: Init

on:
  workflow_call:

jobs:

  init_dev:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache repo
        uses: actions/cache@v3
        with:
          path: |
            ./*
            !.git
          key: vizzu-story-${{ github.run_id }}

      - name: Init dev environment
        run: make dev

      - name: Init dev-js environment
        run: make dev-js
